name: Backend CI

on:
  push:
    paths:
      - "backend/**"
    branches:
      - main
      - develop
      - "feature/**"
  pull_request:
    paths:
      - "backend/**"

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug directory contents
        run: |
          echo "Current directory:"
          pwd
          echo "Workspace directory contents:"
          ls -la ${{ github.workspace }}
          echo "Backend directory contents:"
          ls -la ${{ github.workspace }}/backend

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.2"
          bundler-cache: true
          working-directory: ${{ github.workspace }}/backend

      - name: Generate RSpec files
        working-directory: ${{ github.workspace }}/backend
        env:
          RAILS_ENV: test
        run: bundle exec rails generate rspec:install

      - name: Setup test database
        working-directory: ${{ github.workspace }}/backend
        env:
          RAILS_ENV: test
        run: |
          cp config/database.yml.ci config/database.yml
          bundle exec rails db:create db:schema:load

      - name: Run tests
        working-directory: ${{ github.workspace }}/backend
        env:
          RAILS_ENV: test
        run: bundle exec rspec
