name: Backend CI

on:
  push:
    paths:
      - "backend/**"
    branches:
      - main
      - develop
      - "feature/**"
  pull_request:
    paths:
      - "backend/**"

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.2"
          bundler-cache: true
          working-directory: backend

      - name: Setup test database
        run: |
          cp config/database.yml.ci config/database.yml
          bundle exec rails db:create db:schema:load

      - name: Run tests
        run: bundle exec rspec
