name: Backend CI

on:
  push:
    paths:
      - "backend/**"
    branches:
      - main
      - develop
      - "feature/**"
  pull_request:
    paths:
      - "backend/**"

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug directory structure
        run: |
          echo "Current working directory:"
          pwd
          echo "List workspace root:"
          ls -la
          echo "List .github directory:"
          ls -la .github
          echo "List backend directory:"
          ls -la backend
          echo "Check Gemfile existence:"
          test -f backend/Gemfile && echo "Gemfile exists" || echo "Gemfile not found"

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.2"
          working-directory: backend

      - name: Bundle install
        run: |
          cd backend
          bundle install

      - name: Generate RSpec files
        run: |
          cd backend
          bundle exec rails generate rspec:install

      - name: Setup test database
        run: |
          cd backend
          cp config/database.yml.ci config/database.yml
          bundle exec rails db:create db:schema:load
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/focus_forge_test

      - name: Run tests
        run: |
          cd backend
          bundle exec rspec
        env:
          RAILS_ENV: test
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/focus_forge_test
