name: Backend CI

on:
  push:
    paths:
      - "backend/**"
    branches:
      - main
      - develop
      - "feature/**"
  pull_request:
    paths:
      - "backend/**"

jobs:
  scan_ruby:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.2"
          working-directory: backend
          bundler-cache: true

      - name: Scan for security vulnerabilities
        run: bundle exec brakeman --no-pager

  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.2"
          working-directory: backend
          bundler-cache: true

      - name: Run RuboCop
        run: bundle exec rubocop -f github

  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: backend

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug directory structure
        run: |
          echo "Current working directory:"
          pwd
          echo "Absolute path to Gemfile:"
          realpath Gemfile || echo "Gemfile not found"
          echo "Directory contents:"
          ls -la

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.2"
          working-directory: backend
          bundler-cache: true

      - name: Generate RSpec files
        env:
          RAILS_ENV: test
          BUNDLE_GEMFILE: ${{ github.workspace }}/backend/Gemfile
        run: bundle exec rails generate rspec:install

      - name: Setup test database
        env:
          RAILS_ENV: test
          BUNDLE_GEMFILE: ${{ github.workspace }}/backend/Gemfile
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/focus_forge_test
        run: |
          cp config/database.yml.ci config/database.yml
          bundle exec rails db:create db:schema:load

      - name: Run tests
        env:
          RAILS_ENV: test
          BUNDLE_GEMFILE: ${{ github.workspace }}/backend/Gemfile
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/focus_forge_test
          REDIS_URL: redis://localhost:6379/0
        run: bundle exec rspec
