name: Frontend CI

on:
  push:
    paths:
      - "frontend/**"
    branches:
      - main
      - develop
      - "feature/**"
  pull_request:
    paths:
      - "frontend/**"

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Debug directory structure
        run: |
          echo "Current working directory:"
          pwd
          echo "Directory contents:"
          ls -la

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Clean install dependencies
        run: |
          rm -rf node_modules
          rm -f package-lock.json
          npm install

      - name: Verify next installation
        run: |
          echo "Checking next binary:"
          ls -la node_modules/.bin/next || echo "next binary not found"
          echo "Package contents:"
          cat package.json
          echo "Installed packages:"
          npm list --depth=0

      - name: Run lint
        run: |
          export PATH="$PATH:$(pwd)/node_modules/.bin"
          npm run lint

      - name: Run type check
        run: |
          export PATH="$PATH:$(pwd)/node_modules/.bin"
          npm run type-check

      - name: Build
        run: |
          export PATH="$PATH:$(pwd)/node_modules/.bin"
          npm run build
