name: Frontend CI

on:
  push:
    paths:
      - "frontend/**"
    branches:
      - main
      - develop
      - "feature/**"
  pull_request:
    paths:
      - "frontend/**"

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Debug environment
        run: |
          echo "Node version:"
          node --version
          echo "NPM version:"
          npm --version
          echo "Current working directory:"
          pwd
          echo "Directory contents:"
          ls -la

      - name: Install dependencies
        run: |
          echo "Installing dependencies..."
          npm install
          echo "Installed packages:"
          npm list
          echo "Checking next binary:"
          ls -la node_modules/.bin/next
          echo "Checking next version:"
          ./node_modules/.bin/next --version

      - name: Run lint
        run: ./node_modules/.bin/next lint

      - name: Run type check
        run: npm run type-check

      - name: Build
        run: ./node_modules/.bin/next build
